### ISSUE TITLE
Can you add support for others UTF-8 characters?

### ISSUE THREAD

**Issue by didaquis** [hivickylai/uni-pretty#1]
Can you add support for others UTF-8 characters like `ñ ú ì ü ç` ??

**Comment by victoriadrake** [comment]
Here's the article explaining how the tool works: https://vickylai.com/verbose/unicode-cipher/

Based on the current structure, special characters aren't replaced with their unicode likenesses. A recent contribution (thanks @Haroenv!) means they're left as-is, though.

**Comment by didaquis** [comment]
Thanks! @hivickylai and @Haroenv
